# Generated by Django 4.2.5 on 2023-09-26 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_current_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bid_time',
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
