# Generated by Django 4.2.5 on 2023-10-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='end_time',
        ),
    ]
